
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.16.0.235:3306/gm_platform?useUnicode=true&characterEncoding=utf8
      username: game
      password: gjz1opsdsbJefcDkbC

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  profiles:
    include: template,target

mybatis:
  mapper-locations: classpath:resources/mapper/**/*.xml
  type-aliases-package: com.ydf.generator.entity





